// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/valueField/_ResizableField","dojo/_base/declare dojo/_base/lang dojo/on dojo/string dojo/dom-class dojo/dom-construct dojo/dom-style ./utils/ResizeColumnRowTooltipVisualizer esri/dijit/geoenrichment/utils/PageUnitsConverter esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(A,B,q,C,d,w,p,m,x,n,u,y,k){k=k.geoenrichment.dijit.ReportPlayer.ValueField;
var D={_grid:null,_timeoutHandle:null,setIsBeingResized:function(b,c){this._cleanUp();c&&b.parentGrid&&b.parentGrid.domNode&&(this._grid=b.parentGrid,d.add(this._grid.domNode,"isBeingResized"),this._timeoutHandle=setTimeout(this._cleanUp.bind(this),1E4))},_cleanUp:function(){clearTimeout(this._timeoutHandle);this._grid&&this._grid.domNode&&d.remove(this._grid.domNode,"isBeingResized");this._grid=null}};return A(null,{resizable:!0,hasAllSidesSizers:!1,showSizeLabel:!1,showSizeLabelsInAllRelatedCells:!1,
showColumnRowSizeTooltip:!1,showSizersOnFocus:!1,createSizersOnDemand:!0,resizeRestrictNode:null,allowHorizontalResizing:!0,allowVerticalResizing:!0,sizeLabel:null,_tooltipHandles:null,postCreate:function(){this._tooltipHandles=[];this.inherited(arguments);this.resizable&&this._addCreateSizersTrigger()},_isBeingResized:!1,_isBeingResizedDelayed:!1,_sizers:null,isBeingResized:function(){return this.resizable&&this._sizers?this._isBeingResized||this._sizers.some(function(b){return u.isMouseOver(b)})||
!this.hasAllSidesSizers&&this._sizers.some(function(b){return 0<p.get(b,"opacity")}):!1},wasResizedRecently:function(){return this.isBeingResized()||this._isBeingResizedDelayed},_addCreateSizersTrigger:function(){var b=this;this.createSizersOnDemand||this._updateSizers();q(this.domNode,"mouseover",function(){b._updateSizers()})},_createSizers:function(){var b=this;this.resizable&&!this._sizers&&(this._sizers=(this.hasAllSidesSizers?"e se s sw w nw n ne".split(" "):[this.allowHorizontalResizing?"e":
null,this.allowVerticalResizing?"s":null].filter(function(b){return!!b})).map(function(c){var a=w.create("div",null,b.domNode);b.hasAllSidesSizers?(d.add(a,(b.showSizersOnFocus?"valueField_allSidesSizer_showOnFocus":"valueField_allSidesSizer")+" "+c+"_fieldSizer"),b.fieldCellClass&&d.add(a,"fieldSizer_"+b.fieldCellClass)):"e"===c?(d.add(a,"valueField_widthSizer"),b._tooltipHandles.push(y.setTooltipToNode(a,k.dragToChangeWidth)),b.fieldCellClass&&d.add(a,"widthSizer_"+b.fieldCellClass)):(d.add(a,"valueField_heightSizer"),
b._tooltipHandles.push(y.setTooltipToNode(a,k.dragToChangeHeight)),b.fieldCellClass&&d.add(a,"heightSizer_"+b.fieldCellClass));a._sizerInfo={dir:c,canChangeW:-1!==c.indexOf("w")||-1!==c.indexOf("e"),canChangeH:-1!==c.indexOf("n")||-1!==c.indexOf("s"),canChangeX:-1!==c.indexOf("w"),canChangeY:-1!==c.indexOf("n"),dxDir:-1!==c.indexOf("w")?-1:1,dyDir:-1!==c.indexOf("n")?-1:1};return a}),this._addResizeHandlers())},unitTesting_getSizerByDirection:function(b){this._updateSizers();return this._sizers.filter(function(c){return c._sizerInfo.dir===
b})[0]},_addResizeHandlers:function(){var b=this;this._sizers.forEach(function(c){var a=c._sizerInfo;q(c,"mousedown",function(c){c.stopPropagation();var f;b._setIsBeingResized(!0);b.stopEdit&&b.stopEdit();var h=u.getCursorPosition().clientX,g=u.getCursorPosition().clientY,d=b.getWidth(),n=b.getHeight(),z=h,p=g;c=b._getResisableNodePos();var l={x:c.x,y:c.y,dxShiftSingle:0,dyShiftSingle:0,w:d,h:n,dwSingle:0,dhSingle:0},k=q(document.body,"mousemove",function(c){var e=u.getCursorPosition().clientX,k=
u.getCursorPosition().clientY,r=e-h,t=k-g,r=r*a.dxDir,t=t*a.dyDir;!f&&(a.canChangeW&&r||a.canChangeH&&t)&&(b._onManualSizePreChange(),f=!0);var v=!1;l.dwSingle=0;l.dhSingle=0;a.canChangeW&&r&&(l.w=d+r,l.dwSingle=r,v=!0);a.canChangeH&&t&&(l.h=n+t,l.dhSingle=t,v=!0);l.dxShiftSingle=0;l.dyShiftSingle=0;if(a.canChangeX||a.canChangeY){var m=a.canChangeX?e-z:0,q=a.canChangeY?k-p:0;l.dxShiftSingle=m;l.dyShiftSingle=q;l.x+=m;l.y+=q;z=e;p=k}b._applyResizedCellBox(l,a);v&&(b._onManualSizeChange(a),b.onManualSizeChange());
if(a.canChangeW&&r)b.onManualWidthChange(c);if(a.canChangeH&&t)b.onManualHeightChange(c);b._updateSizers()}),m=q.once(document.body,"mouseup, click",function(){m.remove();k.remove();b._setIsBeingResized(!1)})})})},_setIsBeingResized:function(b){b?(this._isBeingResizedDelayed=this._isBeingResized=!0,d.add(this.domNode,"isBeingResized")):(this._isBeingResized&&this._onManualSizeChangeEnd(),this._isBeingResized=!1,d.remove(this.domNode,"isBeingResized"),n.stealFocus(),setTimeout(function(){this._isBeingResizedDelayed=
!1}.bind(this),100));this._tooltipHandles.forEach(function(c){b?c.suspend():c.resume()});D.setIsBeingResized(this,b)},_getResisableNodePos:function(){return n.position(this.domNode)},_applyResizedCellBox:function(b,c){var a=B.mixin({},b),f=this.resizeRestrictNode&&n.position(this.resizeRestrictNode),e=!1,h=!1;if(a.dxShiftSingle||a.dyShiftSingle){if(f){var g=this._getResisableNodePos();0>a.dxShiftSingle?f.x>=g.x?(a.dxShiftSingle=0,e=!0):(a.dxShiftSingle=Math.max(a.dxShiftSingle,f.x-g.x),a.w-=a.dxShiftSingle-
b.dxShiftSingle):a.x<=f.x?(a.dxShiftSingle=0,e=!0):(a.dxShiftSingle=Math.min(a.dxShiftSingle,a.x-f.x),a.w-=b.dxShiftSingle-a.dxShiftSingle);0>a.dyShiftSingle?f.y>=g.y?(a.dyShiftSingle=0,h=!0):(a.dyShiftSingle=Math.max(a.dyShiftSingle,f.y-g.y),a.h-=a.dyShiftSingle-b.dyShiftSingle):a.y<=f.y?(a.dyShiftSingle=0,h=!0):(a.dyShiftSingle=Math.min(a.dyShiftSingle,a.y-f.y),a.h-=b.dyShiftSingle-a.dyShiftSingle)}this.onNeedShiftPositionFromResizing(a.dxShiftSingle,a.dyShiftSingle)}c.canChangeX&&0===a.dxShiftSingle&&
(e=!0);c.canChangeY&&0===a.dyShiftSingle&&(h=!0);if(a.dwSingle||a.dhSingle)f&&(g=this._getResisableNodePos(),b=f.y+f.h-g.y,a.w=Math.max(3,Math.min(a.w,f.x+f.w-g.x)),a.h=Math.max(3,Math.min(a.h,b))),e||this.setWidth(a.w),h||this.setHeight(a.h)},updateSizers:function(){this._updateSizers()},_updateSizers:function(){function b(){c._sizers.forEach(function(a){var b,e,h=a._sizerInfo,g=c.getWidth(),d=c.getHeight(),k=p.get(a,"width"),m=p.get(a,"height");switch(h.dir){case "e":b=g;e=(d-m)/2;break;case "se":b=
g;e=d;break;case "s":b=(g-k)/2;e=d;break;case "sw":b=0;e=d;break;case "w":b=0;e=(d-m)/2;break;case "nw":e=b=0;break;case "n":b=(g-k)/2;e=0;break;case "ne":b=g,e=0}p.set(a,{left:b+"px",top:e+"px",cursor:h.dir+"-resize",marginLeft:h.canChangeW?-k/2+"px":"",marginTop:h.canChangeH?-m/2+"px":""});if("w"===h.dir||"e"===h.dir)n[30>d?"hide":"show"](a);if("s"===h.dir||"n"===h.dir)n[30>g?"hide":"show"](a)})}this._createSizers();if(this._sizers&&this.hasAllSidesSizers){var c=this;5<p.get(this.domNode,"height")?
b():setTimeout(b,100)}},_onManualSizePreChange:function(){this.setToolbarSuspended&&this.setToolbarSuspended(!0);this.onManualSizePreChange()},_onManualSizeChange:function(b){this.inherited(arguments);this.showSizeLabel&&this._showAndUpdateSizeLabel();this.showSizeLabelsInAllRelatedCells&&this._showAndUpdateRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&("e"===b.dir?m.showColumnTooltip(this):"s"===b.dir&&m.showRowTooltip(this))},_onManualSizeChangeEnd:function(){n.hide(this.sizeLabel);this.setToolbarSuspended&&
this.setToolbarSuspended(!1);this.showSizeLabelsInAllRelatedCells&&this._hideRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&m.removeTooltip();this.onManualSizeChangeEnd()},_showAndUpdateSizeLabel:function(){this.sizeLabel=this.sizeLabel||w.create("div",{"class":"elementSizeLabel"},this.domNode);n.show(this.sizeLabel);setTimeout(function(){if(this.domNode&&!n.isHidden(this.sizeLabel)){var b=this.domNode.clientWidth,c=this.domNode.clientHeight,a=x.pxToPt(b),d=x.pxToPt(c);this.sizeLabel.innerHTML=
C.substitute(k.elementSizeFormatPt,{width:Math.round(a),height:Math.round(d)});a=this.sizeLabel.clientHeight;this.sizeLabel.style.left=(b-this.sizeLabel.clientWidth)/2+"px";this.sizeLabel.style.top=(20<c?(c-a)/2:-a-5)+"px"}}.bind(this))},_showAndUpdateRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(b){b._showAndUpdateSizeLabel()})},_hideRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(b){n.hide(b.sizeLabel)})},_getRelatedCells:function(){return this.parentGrid?
this.parentGrid.getFieldCells().filter(function(b){return b!==this},this):[]},onManualSizePreChange:function(){},onManualSizeChangeEnd:function(){},onManualSizeChange:function(){},onManualWidthChange:function(b){},onManualHeightChange:function(b){},onNeedShiftPositionFromResizing:function(b,c){}})});