// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/playerSupports/_MapSupport",["require","dojo/_base/declare","dojo/Deferred","dojo/when"],function(l,m,n,p){return m(null,{_initPromise:null,_mapBuilder:null,_initMapBuilder:function(){var c=this;if(this._initPromise)return this._initPromise;var a=new n;l(["../core/supportClasses/map/MapBuilder"],function(b){c._mapBuilder=new b({renderMapsFromCalculators:c.renderMapsFromCalculators,getPlayerZoomScale:function(b){var a=c.getCurrentReportContainer();return a&&
a.getPanelZoomScale?a.getPanelZoomScale(b):a&&a.getZoomInfo&&a.getZoomInfo().scale}});a.resolve()});return this._initPromise=a.promise},collectMaps:function(c){return this._mapBuilder?c&&c.allAreas?this._mapBuilder.collectAllAreasMaps():this._mapBuilder.collectAreaMaps(this.getCurrentAnalysisAreaIndex()):[]},_resetMapBuilder:function(){this._mapBuilder&&this._mapBuilder.reset()},_createMap:function(c,a){a=a||{};var b,e={},h=this.getCurrentAnalysisAreaIndex();if(this._reportData.isMultiFeature){b=
[];var k=this._reportData.reverseAnalysisAreasOnMap?this._reportData.analysisAreas.slice().reverse():this._reportData.analysisAreas;k.forEach(function(a,d){var f=this._reportData.reverseAnalysisAreasOnMap?k.length-d-1:d;e[b.length]=f;b.push(a.feature);d=this._reportData.combinedAreasInfo.groups;d&&d.length&&d.some(function(a){return-1!==a.indexes.indexOf(f)})||(a.location&&(e[b.length]=f,b.push(a.location)),a.additionalFeatures&&a.additionalFeatures.forEach(function(a){e[b.length]=f;b.push(a)}))},
this);this._reportData.combinedAreasInfo.groups&&this._reportData.combinedAreasInfo.groups.forEach(function(a){a.location&&(e[b.length]=a.indexes[0],b.push(a.location));a.additionalFeatures&&a.additionalFeatures.forEach(function(d){e[b.length]=a.indexes[0];b.push(d)})})}else{var g=this._reportData.analysisAreas[h];b=[g.feature];g.location&&b.push(g.location);g.additionalFeatures&&(b=b.concat(g.additionalFeatures));b.forEach(function(a,b){e[b]=h},this)}return p(this._initMapBuilder(),function(){this._mapBuilder.setArcgisUrl(this._reportData.config.portalUrl);
this._mapBuilder.setFallbackMapImageInfos(this._reportData.mapImageInfos);var f=this;return this._mapBuilder.createMap(c,{features:b,featureIndexToAreaIndexMap:e,analysisAreas:this._reportData.analysisAreas,areaIndex:h,defaultBasemapId:this._getDefaultBasemapId()||a.defaultBasemapId,webMapId:a.webMapId,additionalLayerInfos:a.additionalLayerInfos,calculatorFieldName:a.calculatorFieldName,locatorPointsControllers:a.locatorPointsControllers,stdPolygonsControllers:a.stdPolygonsControllers,thisAreasHighlightController:a.thisAreasHighlightController,
legendController:a.legendController,fieldData:this._viewModel.dynamicReportInfo.fieldData,geClient:this._viewModel.dynamicReportInfo.geClient,countryID:this._viewModel.dynamicReportInfo.countryID,hierarchy:this._viewModel.dynamicReportInfo.hierarchy,waitForLoad:a.waitForLoad,extent:a.extent,attachmentsStore:this._viewModel.dynamicReportInfo.attachmentsStore,onPanContainer:function(a,b){var c=f.getCurrentReportContainer();if(c=c.getScrollableContainer&&c.getScrollableContainer())c.scrollLeft+=a,c.scrollTop+=
b}})}.bind(this))},_getDefaultBasemapId:function(){return null}})});