// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicSettings","dojo/_base/declare dojo/aspect dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ./chart/SectionDynamicChartSettings ./locator/SectionDynamicLocatorSettings ./areaDetails/SectionDynamicAreaDetailsSettings ./comparison/SectionDynamicComparisonSettings ./map/SectionDynamicMapSettings".split(" "),function(e,d,c,f,g,h,k,l,m,n){return e([f,g],{templateString:"\x3cdiv class\x3d'esriGEReportPlayer_sectionDynamicSettings'\x3e\x3c/div\x3e",
chartSettings:null,locatorSettings:null,areaDetailsSettings:null,comparisonSettings:null,mapSettings:null,_chartSettingsWidget:null,_locatorSettingsWidget:null,_areaDetailsSettingsWidget:null,_comparisonSettingsWidget:null,_mapSettingsWidget:null,postCreate:function(){this._tryInitChartSettings();this._tryInitLocatorSettings();this._tryInitAreaDetailsSettings();this._tryInitComparisonSettings();this._tryInitMapSettings()},_tryInitChartSettings:function(){this.chartSettings&&(this._chartSettingsWidget=
(new h({onSortChart:this.onSortChart.bind(this),onChartToTable:this.onChartToTable.bind(this),onTableToChart:this.onTableToChart.bind(this),onCalcStateChanged:this.onCalcStateChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicSettings_row"},this.domNode)),this.own(this._chartSettingsWidget),this._chartSettingsWidget.setSortingOptions(this.chartSettings.sortingOptions,this.chartSettings.sorting),this._chartSettingsWidget.setViewOptions(this.chartSettings.canViewTable),this._chartSettingsWidget.setToggleCalcStateOptions(this.chartSettings.group))},
_tryInitLocatorSettings:function(){function a(){b._locatorSettingsWidget.setNumPoints(b.locatorSettings.getNumPointsTotal(),b.locatorSettings.getNumPointsShown())}var b=this;this.locatorSettings&&(this._locatorSettingsWidget=(new k({onLocatorFilterChanged:this.onLocatorFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicSettings_row"},this.domNode)),this.own(this._locatorSettingsWidget),this._locatorSettingsWidget.setStatRanges(this.locatorSettings.statRanges),a(),this.own(d.after(this.locatorSettings,
"onContentUpdated",a)))},_tryInitAreaDetailsSettings:function(){function a(){b._areaDetailsSettingsWidget.setNumItems(b.areaDetailsSettings.getNumItemsTotal(),b.areaDetailsSettings.getNumItemsShown())}var b=this;this.areaDetailsSettings&&(this._areaDetailsSettingsWidget=(new l({onAreaDetailsFilterChanged:this.onAreaDetailsFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicSettings_row"},this.domNode)),this.own(this._areaDetailsSettingsWidget),a(),this.own(d.after(this.areaDetailsSettings,
"onContentUpdated",a)))},_tryInitComparisonSettings:function(){function a(){b._comparisonSettingsWidget.setNumAreas(b.comparisonSettings.comparisonTableInfographic.getNumAreasTotal(),b.comparisonSettings.comparisonTableInfographic.getNumAreasShown())}var b=this;this.comparisonSettings&&(this._comparisonSettingsWidget=(new m({onShowChart:this.onShowChart.bind(this),onComparisonFilterChanged:this.onComparisonFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicSettings_row"},this.domNode)),
this.own(this._comparisonSettingsWidget),this._comparisonSettingsWidget.setSettings(this.comparisonSettings),a(),this.own(d.after(this.comparisonSettings.comparisonTableInfographic,"onContentUpdated",a)))},_tryInitMapSettings:function(){this.mapSettings&&(this._mapSettingsWidget=(new n({onLegendVisibilityChanged:this.onLegendVisibilityChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicSettings_row"},this.domNode)),this.own(this._mapSettingsWidget),this._mapSettingsWidget.setLegendVisible(this.mapSettings.showLegend))},
setVisualState:function(a){this._chartSettingsWidget&&this._chartSettingsWidget.setVisualState(a);this._locatorSettingsWidget&&this._locatorSettingsWidget.setVisualState(a);this._areaDetailsSettingsWidget&&this._areaDetailsSettingsWidget.setVisualState(a);this._comparisonSettingsWidget&&this._comparisonSettingsWidget.setVisualState(a);this._mapSettingsWidget&&this._mapSettingsWidget.setVisualState(a)},onSortChart:function(a){},onChartToTable:function(){},onTableToChart:function(){},onCalcStateChanged:function(a){},
onLocatorFilterChanged:function(a){},onAreaDetailsFilterChanged:function(a){},onShowChart:function(a){},onComparisonFilterChanged:function(a){},onLegendVisibilityChanged:function(a){},onClosePopup:function(){}})});