// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicSettingsBuilder","dojo/_base/declare dojo/on dojo/promise/all dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/ReportPlayer/PlayerSelect esri/dijit/geoenrichment/ReportPlayer/PlayerThemes esri/dijit/geoenrichment/ReportPlayer/ReportPlayerState ./chart/_ChartSettingsBuilder ./locator/_LocatorSettingsBuilder ./areaDetails/_AreaDetailsSettingsBuilder ./comparison/_ComparisonSettingsBuilder ./map/_MapSettingsBuilder ./multiFeature/_MultiFeatureSettingsBuilder ./SectionDynamicSettings esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(p,k,q,g,d,r,t,u,v,w,x,y,z,A,B,l,m,e,n,C,h){h=h.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;return p(null,{_section:null,_settingsWidget:null,_settingsToolbar:null,_featureSelectDiv:null,_buttonBar:null,_onButtonBarShowCallbacks:null,constructor:function(a){this._section=a;this._createSettings()},_createSettings:function(){var a=this;q({chartSettings:v.provideChartSettings(this._section),locatorSettings:w.provideLocatorSettings(this._section),areaDetailsSettings:x.provideAreaDetailsSettings(this._section),
comparisonSettings:y.provideComparisonSettings(this._section),mapSettings:z.provideMapSettings(this._section),multiFeatureSettings:A.provideMultiFeatureSettings(this._section)}).then(function(b){if(b.chartSettings||b.locatorSettings||b.areaDetailsSettings||b.comparisonSettings||b.mapSettings||b.multiFeatureSettings)a._addFeatureSelect(b.multiFeatureSettings),a._addLocatorExportButton(b.locatorSettings),a._addSettingsButton(b),(b.locatorSettings&&!b.locatorSettings.hasTitle||b.areaDetailsSettings&&
!b.areaDetailsSettings.hasTitle||b.comparisonSettings)&&g.add(a._settingsToolbar,"needsTopOffset"),a._buttonBar&&1<a._buttonBar.children.length&&g.add(a._buttonBar,"hasMultipleButtons")})},_addFeatureSelect:function(a){var b=this;if(a&&a.canSelectFeatures){a=this._section.viewModel.dynamicReportInfo.analysisAreas.map(function(a,b){return{value:b,label:a.shortName||a.name}});var c=(new r({options:a,value:0,allowRepetitiveSelection:!1,onChange:function(a){var f=b._section.toJson();f.currentFeatureIndex=
a.value;b._section.fromJson(f);c.closePopup();b._settingsWidget&&b._settingsWidget.setVisualState(b._section.getVisualState())}})).placeAt(this._createSettingsToolbar().featureSelectDiv);c.setTheme(t.DARK)}},_addLocatorExportButton:function(a){if(a&&a.canExportToExcel){var b=this._createButton("dijitInline sectionDynamicSettings_exportButton");k(b,"click",function(){a.exportToExcel()});C.setTooltipToNode(b,h.exportInfographicPanel)}},_addSettingsButton:function(a){var b=this,c=!1;if(a.chartSettings||
a.locatorSettings||a.areaDetailsSettings||a.comparisonSettings||a.mapSettings)var f=this._createButton("dijitInline  "+(a.locatorSettings||a.areaDetailsSettings||a.comparisonSettings&&a.comparisonSettings.statRanges?"sectionDynamicSettings_filterButton":"sectionDynamicSettings_settingsButton"),function(){c||(c=!0,n.makePopup(function(){return b._createPopup(a)},this._section,f,{orient:["before","below"]}))})},_createButton:function(a,b){return d.create("div",{"class":a},this._createSettingsToolbar(b).buttonBar)},
_createSettingsToolbar:function(a){function b(a){c._section.isDataDrillingView&&(a=!0);c._buttonBar.style.display=!a||!c._section.isDataDrillingView&&u.isViewingDataDrillingZoom?"none":"";a&&c._onButtonBarShowCallbacks.forEach(function(a){return a()});a||c._closeSettingsPopup();g[a?"add":"remove"](c._section.domNode,"hasDynamicSettingsToolbar")}var c=this;this._settingsToolbar||(this._settingsToolbar=d.create("div",{"class":"sectionDynamicSettings_toolbar"},this._section.domNode),this._adjustToolbarPosition(),
this._featureSelectDiv=d.create("div",{"class":"dijitInline"},this._settingsToolbar),this._buttonBar=d.create("div",{"class":"dijitInline sectionDynamicSettings_buttonBar"},this._settingsToolbar),this._onButtonBarShowCallbacks=[],b(!1),l.isMobileDevice()||this._section.own(k(document.body,"mousemove",function(){b(e.isMouseOver(c._section.domNode)||e.isMouseOver(c._settingsToolbar)||c._settingsWidget&&(e.isMouseOver(c._settingsWidget.domNode)||e.isMouseOver(c._settingsWidget.domNode.parentNode)))})));
a&&this._onButtonBarShowCallbacks.push(a);l.isMobileDevice()&&setTimeout(function(){b(!0)});return{buttonBar:this._buttonBar,featureSelectDiv:this._featureSelectDiv}},_adjustToolbarPosition:function(){if(this._settingsToolbar){var a=this._section.getMapImages()[0];if(a){var a=m.position(a.domNode),b=m.position(this._section.domNode);this._settingsToolbar.style.top=a.y-b.y+"px";this._settingsToolbar.style.right=b.x+b.w-a.x-a.w+"px"}}},_createPopup:function(a){function b(){return c._section.getInfographic().getInnerInfographic()}
var c=this;this._settingsWidget||(this._settingsWidget=new B({chartSettings:a.chartSettings,locatorSettings:a.locatorSettings,areaDetailsSettings:a.areaDetailsSettings,comparisonSettings:a.comparisonSettings,mapSettings:a.mapSettings,onSortChart:function(a){c._closeSettingsPopup();c._section.sortChart(a)},onChartToTable:function(){c._closeSettingsPopup();c._section.chartToTable()},onTableToChart:function(){c._closeSettingsPopup();c._section.tableToChart()},onCalcStateChanged:function(a){c._closeSettingsPopup();
c._section.setChartCalculationState(a)},onLocatorFilterChanged:function(a){b().setSearchText(a.searchText);b().setFilterRanges(a.filterRanges)},onAreaDetailsFilterChanged:function(a){b().setSearchText(a.searchText)},onShowChart:function(a){c._closeSettingsPopup();b().setChartView(a)},onComparisonFilterChanged:function(a){b().setFilterRanges(a.filterRanges)},onLegendVisibilityChanged:function(a){c._section.getMapImages()[0].setLegendVisible(a)},onClosePopup:function(){c._closeSettingsPopup()}}),this._section.own(this._settingsWidget),
this._settingsWidget.setVisualState(this._section.getVisualState()));return this._settingsWidget},_closeSettingsPopup:function(){n.close(this._settingsWidget)},setVisualState:function(a){this._settingsWidget&&this._settingsWidget.setVisualState(a)},notifyShown:function(){this._adjustToolbarPosition()}})});