// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DataDrillingSupport","dojo/_base/declare dojo/on dojo/when dojo/dom-class dojo/dom-construct dojo/dom-style dojo/query ./SimpleInfographicViewModes ../../grid/coreUtils/GridDataUtil ../dataDrilling/DataDrillingLibrary ../dataDrilling/DataDrillingAnimationTypes ../utils/InfographicJsonUtil esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil ../../sections/SectionTypes ../../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(C,n,k,u,p,x,D,y,E,z,v,A,r,B,w,F,G,H,I,t,q){q=q.geoenrichment.dijit.ReportPlayer.Infographics;var J={w:700,h:600};return C(null,{_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);n(this.backToMainViewButton,"click",function(){a._setViewMode(y.VIEW_MAIN,!0)});this.viewModel.dynamicReportInfo&&(t.canPrintDataDrilling(this)&&(w.setTooltipToNode(this.printButton,q.printInfographic),u.add(this.dataDrillingViewDiv,"canPrintDataDrilling"),
n(this.printButton,"click",function(){t.printDataDrilling(a)})),t.canExportDataDrilling(this)&&(w.setTooltipToNode(this.exportButton,q.exportInfographic),u.add(this.dataDrillingViewDiv,"canExportDataDrilling"),n(this.exportButton,"click",function(){t.exportDataDrilling(a)})))},_getCountryID:function(){return this.viewModel.dynamicReportInfo.infographicOptions.countryID},_addDataDrillingHandlers:function(a,b){var e=this,f=E.getFieldInfo(b.getFirstCell()),h=(b=A.getDataDrilling(this._currentInfographicJson,
f.templateName))&&b.sectionJson?b:null,d=(b=b&&b.isStandard&&z.getDrillingOptions(this._getCountryID(),b.standardId||f))&&b[0];if(h||d)a.getTables().forEach(function(a){a.getFieldCells().forEach(function(a){w.setTooltipToNode(a.domNode,null)})}),a.own(n.once(this.domNode,"mouseover",function(){var c=p.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);p.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},c);var b=p.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",
innerHTML:q.drillForMoreData},c);n(c,"click",function(){var a=e._setViewMode(y.VIEW_DATA_DRILLING,!0,c);h?e._renderCustomSectionJson({customDDPanelInfo:h,fieldInfo:f,animationPromise:a}):e._loadStandardDataDrillingView({fieldInfo:f,optionName:d.name,calcState:null,sectionVisualState:null,animationPromise:a})});e._drillingSectionsButtons.push({destroy:function(){p.destroy(c)}});var l=[];a.getTables().forEach(function(a){l.push(a.domNode)});var g=B.uniteNodeBoxes(l,a.domNode);x.set(c,{left:g.x+"px",
top:g.y+"px",width:g.w+"px",height:g.h+"px",lineHeight:g.h+"px"});var k=B.position(c);k.w>g.w&&x.set(c,"left",g.x-(k.w-g.w)/2+"px");b.style.maxWidth=g.w-70+"px";b.style.whiteSpace="normal";b.style.lineHeight="20px"}))},_dataDrillingState:null,_loadStandardDataDrillingView:function(a){var b=a.fieldInfo,e=a.optionName,f=a.calcState,h=a.sectionVisualState,d=a.animationPromise,c=this;this._dataDrillingState={fieldInfo:b,optionName:e,calcState:f,sectionVisualState:h};this._destroyDrillingSections();this._showDDProgress(!0);
return k(function(){var a=c._getDataDrillingPanelDimensions(),d=A.getDataDrilling(c._currentInfographicJson,b.templateName),g=z.getDrillingOptionInfo(c._getCountryID(),d.standardId||b,e,a.w,a.h,f),a=g.enrichInfos;return k(a&&a.length&&c.viewModel.enrichFieldData(a),function(){return g})}(),function(a){return k(c._renderStandardOptionInfo({drillingDataOptionInfo:a,fieldInfo:b,animationPromise:d,optionName:e,calcState:f,sectionVisualState:h}),function(){c._showDDProgress(!1)})})},_renderStandardOptionInfo:function(a){var b=
a.drillingDataOptionInfo,e=a.fieldInfo,f=a.animationPromise,h=a.optionName,d=a.sectionVisualState,c=this,m;this._destroyDrillingSections();var l=this._getDataDrillingPanelSectionParams();l.json={type:G.DETAILS,stack:[b.tableJson]};l.calculationStatesGroup=b.calculationStatesGroup;l.onCalculationStateChanged=function(a){c._loadStandardDataDrillingView({fieldInfo:e,optionName:h,calcState:a,sectionVisualState:m.getVisualState(),animationPromise:null})};return k(f,function(){return r.delay(function(){m=
c._createDataDrillingSection(l);m.fitContentNicely();m.domNode.style.opacity="0.01";return r.delay(function(){m.setVisualState(d);m.domNode.style.opacity=""},100)})})},_renderCustomSectionJson:function(a){var b=a.customDDPanelInfo,e=a.animationPromise,f=a.sectionVisualState,h=this;this._destroyDrillingSections();this._dataDrillingState=null;var d,c=this._getDataDrillingPanelSectionParams();c.json=b.sectionJson;this._showDDProgress(!0);return k(e,function(){return r.delay(function(){d=h._createDataDrillingSection(c);
d.fitContentNicely();d.domNode.style.opacity="0.01";return r.delay(function(){d.setVisualState(f);d.domNode.style.opacity="";h._showDDProgress(!1)})})})},_getDataDrillingPanelSectionParams:function(){var a={"class":"infographicContainer_dataDrillingSection"};a.initialWidth=this._getDataDrillingPanelDimensions().w;a.viewModel=this.viewModel;a.theme=this.theme;a.parentWidget=this;a.hasFixedLayout=!1;a.isDataDrillingView=!0;a.currentFeatureIndex=this.currentFeatureIndex||0;a.initialViewMode=H.PREVIEW_VALUES;
return a},_createDataDrillingSection:function(a){a=this.viewModel.layoutBuilder.createElement("section",a,this.drilledDataViewDiv);this._drillingSections.push(a);a.setResizedHeight(this._getDataDrillingPanelDimensions().h);u[D(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this.dataDrillingAnimationType===v.ZOOM&&this._setUpDDPanelBackgroundColor();return a},_setUpDDPanelBackgroundColor:function(){I.setUpDDPanelBackgroundColor({viewModel:this.viewModel,
theme:this.theme,infographicJson:this._currentInfographicJson,node:this.dataDrillingViewDiv})},_getDataDrillingPanelDimensions:function(){switch(this.dataDrillingAnimationType){case v.ZOOM:return J;default:return{w:this.width,h:this.height}}},_showDDProgress:function(a){F[a?"showProgress":"removeProgress"](this.dataDrillingAnimationType===v.SLIDE?this.domNode:this.dataDrillingViewDiv)},_getDataDrillingState:function(){return this._dataDrillingState},_setDataDrillingState:function(a){a&&this._loadStandardDataDrillingView({fieldInfo:a.fieldInfo,
optionName:a.optionName,calcState:a.calcState,sectionVisualState:a.sectionVisualState,animationPromise:null})},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&p.empty(this.drilledDataViewDiv)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=this._drillingSectionsButtons||[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});
this._drillingSectionsButtons.length=0}})});