// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/PopupManager","./geometry/Extent ./geometry/ScreenPoint ./kernel ./layerUtils ./tasks/query dijit/registry dojo/_base/array dojo/_base/declare dojo/_base/Deferred dojo/_base/lang dojo/has dojo/on dojo/promise/all dojo/Stateful require".split(" "),function(E,y,F,D,G,H,l,q,v,x,I,J,K,L,M){var z;q=q(L,{declaredClass:"esri.PopupManager",enabled:!1,map:null,_mapClickHandle:null,_featureLayersCache:{},constructor:function(a){this._mapClickHandler=x.hitch(this,this._mapClickHandler)},setMap:function(a){if(this.map)if(a!==
this.map)this.unsetMap();else return;this.map=a;this._setupClickHandler()},unsetMap:function(){this.map&&(this.map=null);this._mapClickHandle&&(this._mapClickHandle.remove(),this._mapClickHandle=null)},getMapLayer:function(a){var b;if(a&&(b=a.getLayer())&&(a=b.id,this._featureLayersCache[a])){var c=a.lastIndexOf("_");-1<c&&(a=a.substring(0,c),b=this.map.getLayer(a))}return b},_enabledSetter:function(a){this.enabled=a;this._setupClickHandler()},_setupClickHandler:function(){this._mapClickHandle&&(this._mapClickHandle.remove(),
this._mapClickHandle=null);this.enabled&&this.map&&(this._mapClickHandle=this.map.on("click",this._mapClickHandler))},_mapClickHandler:function(a){var b=this.map.infoWindow,c=a.graphic;b&&this.map.loaded&&(b.clearFeatures&&b.setFeatures?this._showPopup(a):c&&c.getInfoTemplate()&&this._showInfoWindow(c,a.mapPoint))},_showPopup:function(a){var b=this.map,c=b.infoWindow,d=this,g=[],k=[b.graphics].concat(l.map(b.graphicsLayerIds,b.getLayer,b));l.forEach(k,function(a){a&&a.loaded&&a.infoTemplate&&!a.suspended&&
g.push(a)});var p=[];l.forEach(b.layerIds,function(a){(a=b.getLayer(a))&&a.loaded&&!a.suspended&&(d._isImageServiceLayer(a)&&a.infoTemplate?g.push(a):"esri.layers.WMSLayer"===a.declaredClass&&a.getFeatureInfoURL?g.push(a):"esri.layers.ArcGISDynamicMapServiceLayer"!==a.declaredClass&&"esri.layers.ArcGISTiledMapServiceLayer"!==a.declaredClass||!a.infoTemplates||p.push(a))});var q=b.getResolutionForPopup();this._getSubLayerFeatureLayers(p,q).then(function(m){g=g.concat(m);var e=null;a.graphic&&a.graphic.getInfoTemplate()&&
!d._isImageServiceLayer(a.graphic._layer)&&(e=a.graphic);if(g.length||e){var f=d._calculateClickTolerance(g),k=a.screenPoint;m=b.toMap(new y(k.x-f,k.y+f));var f=b.toMap(new y(k.x+f,k.y-f)),p=new E(m.x,m.y,f.x,f.y,b.spatialReference);if(p=p.intersects(b.extent)){var t=new G,n=!!e,u=!0;m=l.map(g,function(c){t.timeExtent=c.useMapTime?b.timeExtent:null;var g=d._isReductionEnabled(c);c=g?c.getFeatureReductionLayer():c;var f,h=d._featureLayersCache[c.id];if(d._isImageServiceLayer(c))t.geometry=a.mapPoint,
u=!1,f=c.queryVisibleRasters(t,{rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0}),f.addCallback(function(){var a=c.getVisibleRasters();n=n||0<a.length;return a});else if("esri.layers.WMSLayer"===c.declaredClass){f=new v;var k=c._getPopupGraphic(b,a.screenPoint);k?(f.resolve([k]),n=!0):f.resolve([])}else h||"function"===typeof c.queryFeatures&&(0===c.currentMode||1===c.currentMode)?(t.geometry=p,f=c.queryFeatures(t),f.addCallback(function(a){var b=[];l.forEach(a.features,function(a){a.visible&&
(b.push(a),h&&a.setResolution(q))});n=n||0<b.length;return b})):(f=new v,k=l.filter(c.graphics,function(a){return a&&a.visible&&p.intersects(a.geometry)}),g&&d._isParentLayer(c,e)&&(g=d._findGraphicById(k,e,"cluster_id"))&&(e=g),n=n||0<k.length,f.resolve(k));return f});e&&(f=new v,f.resolve([e]),m.unshift(f));l.some(m,function(a){return!a.isFulfilled()})||n?(c.setFeatures(m),c.show(a.mapPoint,{closestFirst:u})):(c.hide(),c.clearFeatures())}}})},_getSubLayerFeatureLayers:function(a,b,c){b=b||null;
var d=c||new v,g=[];c=a.length;var k=this.map.getScale(),p=!1,q=this,m=0;a:for(;m<c;m++){var e=a[m],f=e.dynamicLayerInfos||e.layerInfos;if(f){var A=null;e._params&&(e._params.layers||e._params.dynamicLayers)&&(A=e.visibleLayers);for(var A=D._getVisibleLayers(f,A),y=D._getLayersForScale(k,f),t=f.length,n=0;n<t;n++){var u=f[n],r=u.id,w=e.infoTemplates[r];if(!u.subLayerIds&&w&&w.infoTemplate&&-1<l.indexOf(A,r)&&-1<l.indexOf(y,r)){if(!z){p=!0;break a}var B=e.id+"_"+r,h=this._featureLayersCache[B];h&&
h.loadError||(h||((h=w.layerUrl)||(h=u.source?this._getLayerUrl(e.url,"/dynamicLayer"):this._getLayerUrl(e.url,r)),h=new z(h,{id:B,drawMode:!1,mode:z.MODE_SELECTION,outFields:this._getOutFields(w.infoTemplate),resourceInfo:w.resourceInfo,source:u.source}),this._featureLayersCache[B]=h),h.setDefinitionExpression(e.layerDefinitions&&e.layerDefinitions[r]),h.setGDBVersion(e.gdbVersion),h.setInfoTemplate(w.infoTemplate),h.setMaxAllowableOffset(b),h.setUseMapTime(!!e.useMapTime),e.layerDrawingOptions&&
e.layerDrawingOptions[r]&&e.layerDrawingOptions[r].renderer&&h.setRenderer(e.layerDrawingOptions[r].renderer),g.push(h))}}}}if(p){var x=new v;M(["./layers/FeatureLayer"],function(a){z=a;x.resolve()});x.then(function(){q._getSubLayerFeatureLayers(a,b,d)})}else{var C=[];l.forEach(g,function(a){if(!a.loaded){var b=new v;J.once(a,"load, error",function(){b.resolve()});C.push(b.promise)}});C.length?K(C).then(function(){g=l.filter(g,function(a){return!a.loadError&&a.isVisibleAtScale(k)});d.resolve(g)}):
(g=l.filter(g,function(a){return a.isVisibleAtScale(k)}),d.resolve(g))}return d.promise},_getLayerUrl:function(a,b){var c=a.indexOf("?");return-1===c?a+"/"+b:a.substring(0,c)+"/"+b+a.substring(c)},_getOutFields:function(a){var b;a.info&&"esri.dijit.PopupTemplate"===a.declaredClass?(b=[],l.forEach(a.info.fieldInfos,function(a){var c=a.fieldName&&a.fieldName.toLowerCase();c&&"shape"!==c&&0!==c.indexOf("relationships/")&&b.push(a.fieldName)})):b=["*"];return b},_calculateClickTolerance:function(a){var b=
6,c,d;l.forEach(a,function(a){if(c=a.renderer)"esri.renderer.SimpleRenderer"===c.declaredClass?((d=c.symbol)&&d.xoffset&&(b=Math.max(b,Math.abs(d.xoffset))),d&&d.yoffset&&(b=Math.max(b,Math.abs(d.yoffset)))):"esri.renderer.UniqueValueRenderer"!==c.declaredClass&&"esri.renderer.ClassBreaksRenderer"!==c.declaredClass||l.forEach(c.infos,function(a){(d=a.symbol)&&d.xoffset&&(b=Math.max(b,Math.abs(d.xoffset)));d&&d.yoffset&&(b=Math.max(b,Math.abs(d.yoffset)))})});return b},_showInfoWindow:function(a,b){var c=
this.map.infoWindow,d=a.geometry;b=d&&"point"===d.type?d:b;d=a.getContent();c.setTitle(a.getTitle());d&&x.isString(d.id)&&(a=H.byId(d.id))&&a.set&&/_PopupRenderer/.test(a.declaredClass)&&a.set("showTitle",!1);c.setContent(d);c.show(b)},_findGraphicById:function(a,b,c){var d,g=(b=b.attributes)&&b[c];l.some(a,function(a){var b=a.attributes;b&&b[c]===g&&(d=a);return!!d});return d},_isParentLayer:function(a,b){b=b&&b.getLayer();return a&&b===a},_isReductionEnabled:function(a){return a&&a.isFeatureReductionActive&&
a.isFeatureReductionActive()},_isImageServiceLayer:function(a){return"esri.layers.ArcGISImageServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass}});I("extend-esri")&&(F.PopupManager=q);return q});