// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicsPageStack","dojo/_base/declare dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ../themes/BackgroundThemeUtil esri/dijit/geoenrichment/utils/async/AsyncQueue esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../sections/sectionUtils/SectionJsonUtil esri/dijit/geoenrichment/utils/ColorUtil dojo/i18n!esri/nls/jsapi".split(" "),function(n,
g,p,q,r,t,u,l,v,w,k){function m(a){var b=l.getParentBox(a);return b&&b.w?b:v.calcSectionJsonBox(a)}k=k.geoenrichment.dijit.ReportPlayer.Infographics;return n([p,q],{templateString:"\x3cdiv class\x3d'esriGEReportPlayer_infographicsPageStack'\x3e\x3c/div\x3e",nls:k,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,scaleSectionsToFit:!0,_asyncQueue:null,_sections:null,_maxWidth:0,_panelIndexToScaleCache:null,postCreate:function(){this.inherited(arguments);this._sections=[];this._panelIndexToScaleCache=
{}},setItems:function(a){var b=this;this._destroySections();this._asyncQueue=new t;this._calcMaxWidth(a);a.forEach(function(a,c){b._asyncQueue.add(function(){b._createPanel(a,c)},{delayAfter:0})});return this._asyncQueue.getPromise()},_calcMaxWidth:function(a){this._maxWidth=0;a.forEach(function(a){if(a=m(a))this._maxWidth=Math.max(this._maxWidth,a.w)},this)},_createPanel:function(a,b){var f=g.create("div",{"class":"infographicPageStack_infographicRow"},this.domNode),c=g.create("div",{"class":"infographicPageStack_infographicSectionNode"},
f),d={"class":"adjustableGrid_inCellSection"};d.json=a;d.viewModel=this.viewModel;d.theme=this.theme;d.parentWidget=this;d.initialWidth=this._maxWidth;d.hasFixedLayout=!1;d.currentFeatureIndex=this.currentFeatureIndex;d.isPagePanelSection=!0;d.initialViewMode=u.PREVIEW_VALUES;d=this.viewModel.layoutBuilder.createElement("section",d,c);this._sections.push(d);var e=m(a);d.setResizedHeight(e.h);d.setWidth(e.w);c.style.width=e.w+"px";c.style.height=e.h+"px";if(this.scaleSectionsToFit){var h=(this._maxWidth+
2)/(e.w+2);f.style.width=this._maxWidth+"px";f.style.height=(e.h+2)*h+"px";f.style.marginBottom="10px";c.style.transform="scale("+h+")";c.style.webkitTransform="scale("+h+")";c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.margin="0px"}else c.style.margin="10px";this._panelIndexToScaleCache[b]=h||1;this._renderPanelBackground(c,a,e)},_renderPanelBackground:function(a,b,f){b=l.getParentStyle(b);var c=this.viewModel.getDocumentDefaultStyles(this.theme);c?(a=g.create("div",{"class":"esriGEAbsoluteStretched"},
a,"first"),r.applyBackgroundImageFromSettings(a,c.backgroundImage,{documentOptions:this.parentWidget.documentOptions,pos:f})||(a.style.backgroundColor=b&&b.backgroundColor&&!w.isTransparent(b.backgroundColor)?b.backgroundColor:c.backgroundColor)):a.style.backgroundColor=b&&b.backgroundColor},getSections:function(){return this._sections},getPanelScaleAt:function(a){return this._panelIndexToScaleCache[a]||1},notifyShown:function(){this._sections.forEach(function(a){a.notifyShown()})},_destroySections:function(){this._asyncQueue&&
this._asyncQueue.destroy();this._asyncQueue=null;this._sections.forEach(function(a){a.destroy()});this._sections.length=0;g.empty(this.domNode)},destroy:function(){this._destroySections();this.inherited(arguments)}})});