// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/InfographicContainer.html":'\x3cdiv class\x3d"esriGEReportPlayer_infographicContainer esriGEAbsoluteStretched"\x3e\r\n    \x3cdiv class\x3d"infographicContainer_viewDiv" data-dojo-attach-point\x3d"viewDiv"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicContainer","require dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicTypes esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/WaitingUtil esri/dijit/geoenrichment/ReportPlayer/config dojo/text!../templates/InfographicContainer.html".split(" "),function(h,k,g,l,e,m,n,b,f,p,q,r){return k([m,
n],{templateString:r,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,adjustElementsWhenResized:!1,_pendingResizeFlag:!1,_pendingUpdateFlag:!1,_currentInfographic:null,getInnerInfographic:function(){return this._currentInfographic},getContentInitPromise:function(){return this._infographicInitPromise},_getTypeToClassPathMap:function(){var a={};a[b.STATIC]=q.modules.dataDrilling?"./simpleInfographic/SimpleInfographicWithDataDrilling":"./simpleInfographic/SimpleInfographic";a[b.ATTACHMENTS]=
"./AttachmentsInfographic";a[b.AREA_DETAILS]="./areaDetails/AreaDetailsInfographic";a[b.LOCATOR_TABLE]="./locator/LocatorTableInfographic";a[b.COMPARISON_TABLE]="./comparison/ComparisonTableInfographic";a.dynamic="./dynamic/DynamicInfographic";return a},_getRelativeRequire:function(){return h},_infographicInitPromise:!1,_lastAppliedJson:null,updateInfographic:function(a){var c=this;if(this.viewDiv&&a&&b.isSupported(a.type)&&!this._infographicInitPromise){this._lastAppliedJson=a;this._type=a.type;
if(this._currentInfographic)return this._currentInfographic.updateInfographic(a);var t=this._getTypeToClassPathMap()[b.isDynamic(a.type)?"dynamic":a.type],d=new l;this._getRelativeRequire()([t],function(a){d.resolve(a)});p.showProgressPromise(this.domNode,d.promise);this.onContentLoadingStart();this._infographicInitPromise=d.promise.then(function(b){c._createInfographicForClass(a,b);c.onContentLoadingEnd()});return this._infographicInitPromise.then(function(){c._infographicInitPromise=null;if(f.isNodeInLayout(c.domNode))return c._currentInfographic.updateInfographic(a);
c._pendingUpdateFlag=!0})}},_createInfographicForClass:function(a,c){var b=this,d=g.mixin({viewModel:this.viewModel,theme:this.theme,parentWidget:this,currentFeatureIndex:this.currentFeatureIndex,width:this.width,height:this.height,adjustElementsWhenResized:this.adjustElementsWhenResized,onContentLoadingStart:function(){b.onContentLoadingStart()},onContentLoadingEnd:function(){b.onContentLoadingEnd()}},this._prepareCreationParameters(a),d);this._currentInfographic=new c(d);this._currentInfographic.placeAt(this.viewDiv);
return this._currentInfographic},_prepareCreationParameters:function(a){return null},_type:null,getType:function(){return this._type},width:null,height:null,resize:function(a,b){void 0!==a&&(this.width=a,this.height=b);e(this._infographicInitPromise,function(){f.isNodeInLayout(this.domNode)?this._currentInfographic&&this._currentInfographic.resize(this.width,this.height):this._pendingResizeFlag=!0}.bind(this))},getPreferredHeight:function(){return this._currentInfographic.getPreferredHeight&&this._currentInfographic.getPreferredHeight()},
collapseContent:function(){this._currentInfographic.collapseContent&&this._currentInfographic.collapseContent()},toJson:function(){return this._currentInfographic?this._currentInfographic.toJson():this._lastAppliedJson&&g.clone(this._lastAppliedJson)},getVisualState:function(){return this._currentInfographic&&this._currentInfographic.getVisualState&&this._currentInfographic.getVisualState()},setVisualState:function(a){return this._currentInfographic&&this._currentInfographic.setVisualState&&this._currentInfographic.setVisualState(a)},
notifyShown:function(){e(this._infographicInitPromise,function(){if(f.isNodeInLayout(this.domNode)){this._pendingResizeFlag&&this.resize();this._pendingResizeFlag=!1;var a=this._pendingUpdateFlag&&this._currentInfographic.updateInfographic(this._lastAppliedJson);this._pendingUpdateFlag=!1;e(a,function(){this._currentInfographic&&this._currentInfographic.notifyShown&&this._currentInfographic.notifyShown()}.bind(this))}}.bind(this))},collectFieldInfos:function(){return this._currentInfographic&&this._currentInfographic.collectFieldInfos&&
this._currentInfographic.collectFieldInfos()},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},destroy:function(){this._currentInfographic&&this._currentInfographic.destroy();this.inherited(arguments)}})});