// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/std/LoadedFeaturesSyncronizer","dojo/_base/declare dojo/_base/lang dojo/when dojo/promise/all esri/graphic esri/layers/GraphicsLayer esri/geometry/jsonUtils esri/renderers/jsonUtils esri/renderers/SimpleRenderer esri/dijit/PopupTemplate ./DefaultSymbolRenderer ./FeatureGeometryLoader esri/dijit/geoenrichment/ReportPlayer/countryConfig ../../../../../dataProvider/supportClasses/AreasInfoTemplateBuilder esri/dijit/geoenrichment/utils/SymbolUtil".split(" "),
function(m,g,h,n,p,q,r,t,u,v,w,k,x,y,z){return m(null,{controller:null,layerSorter:null,map:null,countryID:null,hierarchy:null,calculatorFieldName:null,_levelIdToLayerCache:null,_showFeaturesCache:null,_isDestroyed:!1,constructor:function(a){g.mixin(this,a);this._levelIdToLayerCache={};this._showFeaturesCache={}},syncWithShownFeatures:function(){if(this._isDestroyed)console.log(Error("Attempt to use syncronizer after destroying."));else{var a=this.controller.getShownFeatureAttributes(),b={};a&&a.forEach(function(a){var c=
a.StdGeographyLevel+";"+a.StdGeographyID;b[c]=a;this._showFeaturesCache[c]||this._addFeatureByAttributes(a)},this);for(var c in this._showFeaturesCache)b[c]||this._removeFeatureByAttributes(this._showFeaturesCache[c]);this._showFeaturesCache=b}},loadAllFeatures:function(){var a=this;return n(this.controller.getAllFeatureAttributes().map(function(b){return a._getGeometryJsonByAttributes(b)}))},_addFeatureByAttributes:function(a){var b=a.StdGeographyName,c=this._getLayerForLevelId(a.StdGeographyLevel);
if(c){var f=this.controller.getAttributeFields().map(function(b){return{label:b.label,value:b.formatFunction(a[b.name])}}),b=new v({title:b||"",fieldInfos:[],description:y.buildAttributesTable(null,f)}),d=new p({attributes:a,geometry:null});d.setInfoTemplate(b);var e;if(!c.renderer){var b=this.controller.getRendererJson(this.calculatorFieldName),l=(b?t.fromJson(g.clone(b)):w.getDefaultStdRenderer()).getSymbol(d);e=z.simpleFillSymbolToPictureFillSymbol(l).then(function(a){c.setRenderer(new u(a||l))})}h(this._getGeometryJsonByAttributes(a),
function(a){a&&(d.setGeometry(r.fromJson(a)),h(e,function(){c.add(d)}))})}},_getGeometryJsonByAttributes:function(a){var b=this,c=a.StdGeographyLevel,f=a.StdGeographyID,d="stdGeometry_"+this.map.spatialReference.wkid,e=a[d]&&JSON.parse(a[d]);return e?e:k.canLoad()&&k.getFeatureGeometry({countryID:this.countryID,hierarchy:this.hierarchy,levelId:c,featureId:f,outSR:{wkid:this.map.spatialReference.wkid}}).then(function(c){if(b._isDestroyed)return null;a[d]=JSON.stringify(c);return c})},_removeFeatureByAttributes:function(a){var b=
this._levelIdToLayerCache[a.StdGeographyLevel];if(b){var c=b.graphics.filter(function(b){return b.attributes.StdGeographyID===a.StdGeographyID})[0];c&&b.remove(c)}},_getLayerForLevelId:function(a){if(!this._levelIdToLayerCache[a]){if(!this._canShowLayerForLevelId(a))return null;var b=this._levelIdToLayerCache[a]=new q;this.layerSorter.registerLayerInfo({layer:b,type:this.layerSorter.STD_POLYGONS,preferredIndex:this.controller.getLayerIndex(this.calculatorFieldName,a),geometryType:"esriGeometryPolygon"});
this._provideNameForLayer(b,a);this.onLayerCreated(b,a)}return this._levelIdToLayerCache[a]},_canShowLayerForLevelId:function(a){var b=this.controller.getRendererJson(this.calculatorFieldName);return!b||(b=b.uniqueValueInfos.filter(function(b){return b.value===a})[0],!b||b.symbol.color[3]||b.symbol.outline&&b.symbol.outline.color[3])?!0:!1},_provideNameForLayer:function(a,b){a.name=x.getGeographiesModel().getLevelPluralName(b);a.onVisibilityChange()},onLayerCreated:function(a,b){},destroy:function(){this._isDestroyed=
!0;this._levelIdToLayerCache=this.controller=null}})});