// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/std/StdPolygonsController","dojo/_base/declare dojo/Deferred dojo/on dojo/sniff dojo/promise/all dijit/Destroyable esri/dijit/geoenrichment/ReportPlayer/countryConfig".split(" "),function(h,k,f,g,l,m,n){return h(m,{_calculatorName:null,_hasRegisteredLayers:!1,constructor:function(a){this._calculatorName=a;this._layerIndexes={};this._rendererJsons={};this._mapInfos={};this._graphicLayerInfos={}},getCalculatorName:function(){return this._calculatorName},
_rendererJsons:null,getRendererJson:function(a){return this._rendererJsons[a]},setRendererJson:function(a,b){this._rendererJsons[a]=b},_layerIndexes:null,getLayerIndex:function(a,b){var c=n.getGeographiesModel().getLevels(),d=-1;c.some(function(a,c){if(a.id===b)return d=c,!0});return this._layerIndexes[a]+d/c.length},setLayerIndex:function(a,b){this._layerIndexes[a]=b},_mapInfos:null,getMapInfo:function(a){return this._mapInfos[a]},getMapInfos:function(){var a=[],b;for(b in this._mapInfos)a.push(this._mapInfos[b]);
return a},setMapInfo:function(a,b){this._mapInfos[a]=b},_attributeFields:null,getAttributeFields:function(){return this._attributeFields},setAttributeFields:function(a){this._attributeFields=a},_shownFeatureAttributes:null,_featuresChangedHandlers:null,getShownFeatureAttributes:function(){return this._shownFeatureAttributes},setShownFeaturesChangedListener:function(a){this._featuresChangedHandlers=this._featuresChangedHandlers||[];this._featuresChangedHandlers.push(a)},setShownFeatureAttributes:function(a){this._shownFeatureAttributes=
a;this._featuresChangedHandlers&&this._featuresChangedHandlers.forEach(function(a){a()})},_allFeatureAttributes:null,_loadAllFeaturesHandlers:null,getAllFeatureAttributes:function(){return this._allFeatureAttributes},setAllFeatureAttributes:function(a){this._allFeatureAttributes=a},setLoadAllFeaturesListener:function(a){this._loadAllFeaturesHandlers=this._loadAllFeaturesHandlers||[];this._loadAllFeaturesHandlers.push(a)},loadAllFeatures:function(){return this._loadAllFeaturesHandlers&&l(this._loadAllFeaturesHandlers.map(function(a){return a()}))},
_highlightTableForAttributesFunc:null,_registerTableDfd:null,registerTable:function(a){this._highlightTableForAttributesFunc=a.highlightTableForAttributes;this._registerTableDfd=new k;this._hasRegisteredLayers&&this._registerTableDfd.resolve();return this._registerTableDfd.promise},_graphicLayerInfos:null,setStdPolygonsLayer:function(a,b,c,d){this._unSetInfo(a);b={graphicsLayer:b,getGraphicForAttributesFunc:d.getGraphicForAttributesFunc,setGraphicHighlightedFunc:d.setGraphicHighlightedFunc,layerMouseOverHandle:null,
layerMouseOutHandle:null,highlightedGraphic:null};this._graphicLayerInfos[a]=b;this._addLayerListeners(b,c);this._hasRegisteredLayers||(this._hasRegisteredLayers=!0,this._registerTableDfd&&this._registerTableDfd.resolve())},_addLayerListeners:function(a,b){var c=this,d=a.graphicsLayer,e;a.layerMouseOverHandle=f(g("touch")?b:d,g("touch")?"mouse-down, mouse-move":"mouse-move",function(b){b.graphic&&b.graphic._graphicsLayer===d&&e!==b.graphic&&(a.layerMouseOutHandle&&a.layerMouseOutHandle.remove(),a.layerMouseOutHandle=
null,e&&a.setGraphicHighlightedFunc(e,!1),e=b.graphic,c._highlightTableForAttributesFunc(e.attributes),a.setGraphicHighlightedFunc(e,!0),a.layerMouseOutHandle=f.once(d,"mouse-out",function(b){c._highlightTableForAttributesFunc(null);e&&a.setGraphicHighlightedFunc(e,!1);e=null}))})},highlightGraphicForAttributes:function(a){for(var b in this._graphicLayerInfos){var c=this._graphicLayerInfos[b];c.highlightedGraphic&&(c.setGraphicHighlightedFunc(c.highlightedGraphic,!1),c.highlightedGraphic=null);if(a){var d=
c.getGraphicForAttributesFunc(a);d&&(c.setGraphicHighlightedFunc(d,!0),c.highlightedGraphic=d)}}},_unSetInfo:function(a){var b=this._graphicLayerInfos[a];delete this._graphicLayerInfos[a];b&&(b.layerMouseOverHandle&&b.layerMouseOverHandle.remove(),b.layerMouseOutHandle&&b.layerMouseOutHandle.remove())},_unSetLayers:function(){Object.keys(this._graphicLayerInfos).forEach(this._unSetInfo.bind(this));this._graphicLayerInfos={}},destroy:function(){this._unSetLayers()}})});