// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/GEUtil","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/promise/all dojox/uuid/generateRandomUuid esri/kernel esri/request esri/urlUtils esri/dijit/geoenrichment/utils/requests/UniversalClient esri/dijit/geoenrichment/utils/UrlUtil ./stdGeographies/StdGeographiesModel".split(" "),function(t,l,m,n,u,v,w,h,x,q,y,z){function f(a,b){a=x.urlToObject(a);if(b&&(b=l.mixin(a.query||{},b),!b.token)){var c=w.id.credentials[0];
b.token=c&&c.token}return{url:a.path,taskParams:b}}function e(a){g||(g=new r(k));return!a||g.initialized?g:g.initialize()}var r=t(null,{url:null,_geInfo:null,_capabilities:null,_supportedOperations:null,constructor:function(a){this.url=a},_initDfd:null,initialized:!1,initialize:function(){var a=this;if(this._initDfd)return this._initDfd.promise;this._initDfd=new m;h({url:f(this.url).url+"/Geoenrichment",content:{f:"json"},handleAs:"json"}).then(function(b){a.initWithJson(b)});return this._initDfd.promise},
initWithJson:function(a){this._geInfo=a;this._capabilities={};this._supportedOperations={};a.capabilities&&a.capabilities.forEach(function(a){this._capabilities[a.toLowerCase()]=!0},this);a.supportedOperations&&a.supportedOperations.forEach(function(a){this._supportedOperations[a.toLowerCase()]=!0},this);this._initDfd=this._initDfd||new m;this._initDfd.resolve();this.initialized=!0},hasCapability:function(a){return this._capabilities[a.toLowerCase()]},supportsOperation:function(a){return this._supportedOperations[a.toLowerCase()]},
enrich:function(a){a=f(this.url,a);a.taskParams.AddDerivativeVariables="all";return h({url:a.url+"/Geoenrichment/Enrich",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.FeatureSet||[]})},stdGeographyQuery:function(a){a=f(this.url,a);return h({url:a.url+"/StandardGeographyQuery/execute",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.features||[]})},getDataCollections:function(a,b,c){c=f(this.url,c);return h({url:c.url+"/Geoenrichment/DataCollections/"+
a+"/"+b,content:c.taskParams,handleAs:"json"}).then(function(a){return a.DataCollections})},_contriesCache:{},getCountryInfo:function(a){var b=this;if(!this._contriesCache[a]){var c=f(this.url,{f:"json"});this._contriesCache[a]=h({url:c.url+"/Geoenrichment/Countries/"+a,content:c.taskParams,handleAs:"json"}).then(function(c){var d=c.countries[0],e={};return u(d.hierarchies.map(function(c){return n(b.getStdGeographyModel(a,c.ID),function(a){e[c.ID]=a})})).then(function(){return{country:d,geographiesModels:e}})})}return this._contriesCache[a]},
_stdModelCache:null,getStdGeographyModel:function(a,b){b=b||"census";this._stdModelCache=this._stdModelCache||{};var c=a+b;if(!this._stdModelCache[c]){var d=f(this.url,{f:"json"});this._stdModelCache[c]=h({url:d.url+"/Geoenrichment/StandardGeographyLevels/"+a+"/"+b,content:d.taskParams,handleAs:"json"}).then(function(c){return new z({countryID:a,hierarchyID:b,levels:c.geographyLevels[0].hierarchies[0].levels})})}return this._stdModelCache[c]},formatReport:function(a){a=f(this.url,a);return q.request({url:a.url,
urlSuffix:"Geoenrichment/FormatReport"},{handleAs:"bin",content:a.taskParams}).then(function(a){return a&&a.data&&"text/plain"===a.data.type?null:a})},_tasksHash:{},createReport:function(a){var b=f(this.url,a),c=v();this._tasksHash[c]={taskName:"createReport",taskParams:l.clone(a)};return q.request({url:b.url,urlSuffix:"Geoenrichment/createReport"},{handleAs:"text",content:b.taskParams}).then(function(a){return{taskID:c,result:a}})},consumeCredits:function(a){if(a=this._tasksHash[a])return a=l.clone(a),
delete a.taskParams.forStorage,this[a.taskName](a.taskParams)},_dataLayersCache:{},getLayerInfos:function(a){this._dataLayersCache[a]||(this._dataLayersCache[a]=this._getLayerInfos(a));return this._dataLayersCache[a]},_getLayerInfos:function(a){var b=f(this.url,{f:"json"});return h({url:b.url+"/Geoenrichment/DataLayers/"+a,content:b.taskParams,handleAs:"json"}).then(function(a){return a&&a.layers||[]}).otherwise(function(a){console.log(a);return[]})},getLayerInfo:function(a,b){var c=a+"_"+b;this._dataLayersCache[c]||
(this._dataLayersCache[c]=this._getLayerInfo(a,b));return this._dataLayersCache[c]},_getLayerInfo:function(a,b){var c=f(this.url,{f:"json"});return h({url:c.url+"/Geoenrichment/DataLayers/"+a+"/"+b,content:c.taskParams,handleAs:"json"}).then(function(a){return a&&a.layer}).otherwise(function(a){console.log(a);return null})}}),d={},k,p=new m;d.setGeoenrichmentUrl=function(a){(k=a||k)&&y.registerCORS(k);!p.promise.isFulfilled()&&p.resolve()};d.canMakeRequests=function(){return!!k};d.getInitPromise=
function(){return p.promise};d.GEClient=r;var g;d.getClient=function(){return e()};d.initialize=function(){return e(!0)};d.initWithJson=function(a,b){d.setGeoenrichmentUrl(a);e().initWithJson(b)};d.enrich=function(a){return e().enrich(a)};d.stdGeographyQuery=function(a){return e().stdGeographyQuery(a)};d.getDataCollections=function(a,b,c){return e().getDataCollections(a,b,c)};d.formatReport=function(a){return e().formatReport(a)};d.createReport=function(a){return e().createReport(a)};d.consumeCredits=
function(a){return e().consumeCredits(a)};d.getLayerInfos=function(a){return e().getLayerInfos(a)};d.hasCapability=function(a){return n(e(!0),function(){return g&&g.hasCapability(a)})};d.supportsOperation=function(a){return n(e(!0),function(){return g&&g.supportsOperation(a)})};d.getCountryInfo=function(a){return e().getCountryInfo(a)};d.getStdGeographyModel=function(a,b){return e().getStdGeographyModel(a,b)};return d});