// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/ReportDataProcessor","dojo/when dojo/promise/all dojo/Deferred ./tasks/EnrichAreasTask ./tasks/RunReportTask ./AreaDataUtil ./AreaCalculatorsUtil ./CustomReportsManager ./attachments/AttributesUtil esri/dijit/geoenrichment/utils/DateUtil ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldLibrary ../../core/infographics/dataDrilling/EnrichUtil ../../core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil".split(" "),
function(g,l,q,r,t,u,h,m,v,n,p,w,x){return{populateReportDataFromAttachmentsStore:function(b,a){var c=[];a.setCurrentAnalysisAreaIndex&&a.setCurrentAnalysisAreaIndex(0);c.push(g(a.getNotes(),function(a){a&&a.length&&(b.fieldData.metadata[p.SITENOTE_FIELD_NAME]=a[0].text,b.fieldData.metadata[p.SITENOTES_FIELD_NAME]=a.map(function(a){return a.text}).join("\x3cbr/\x3e\x3cbr/\x3e"))}));c.push(g(a.getAttributes(),function(a){if(!a||!a.length)return null;var c={attributes:{}};a.forEach(function(a){c.attributes[a.name]=
v.formatAttributeValue(a)});b.analysisAreas.forEach(function(a,d){(a=b.fieldData.areaData[d])&&h.addFeatureAttributesCalculator(c,a)})}));return l(c)},runReportAndGetData:function(b){return g(m.getCustomReportByID(b),function(a){return(new t).execute({analysisAreas:b.analysisAreas,countryID:b.countryID,hierarchy:a.hierarchy,report:{reportID:a.reportID,portalUrl:a.templateData.getPortalUrl(!0),modified:a.modified},cacheResult:!0}).then(function(b){return{taskID:b.taskID,selectedReport:a,areaData:b.areaData}},
function(a){b.fieldData.errors.push(a);return(new q).reject(a)})})},applyRunReportAndGetDataResults:function(b,a){b&&b.areaData&&(a.fieldData.runReportTaskID=b.taskID,a.fieldData.areaData=b.areaData,a.analysisAreas&&this._reportDataFromAreas(a.analysisAreas,a.fieldData.areaData),b.selectedReport&&this._reportDataFromReport(b.selectedReport,a.fieldData,a.combinedAreasInfo))},_reportDataFromAreas:function(b,a){b.forEach(function(b,e){if(e=a[e])h.addFeatureAttributesCalculator(b.feature,e),h.addAreaInfoCalculator(b,
e)})},_reportDataFromReport:function(b,a,c){a=a.metadata;b&&!a.Title&&(a.Title=b.title);a.Source="Esri";a.Date=n.getReportFooterDate();a.Copyright="\u00a9"+n.getFullYear()+" Esri";a.ProductLabel="";a.ProductUrl="";a.PhoneNumber="";a.TrialUrlText="";b.isMultiFeature&&(a.SITE_NAME=c.locationName||c.name,a.STORE_NAME=c.locationName||c.name,a.AREA_DESC2=c.description||c.name,a.STORE_ADDR=c.address)},enrichFieldData:function(b,a){function c(b,c,d){function e(b){return a.fieldData.areaData.every(function(c,
f){return void 0!==u.getAreaDataValue({fieldName:b,fieldData:a.fieldData,calculatorName:d,featureIndex:f,ignoreMetadata:!0})})}d=d||x.ENRICHED_DATA_NO_LEVELS;var f=[],k={};b.forEach(function(a){e(a.fieldName)||(f.push(a.mapTo),k[a.mapTo]=a.fieldName,k[a.mapTo.substr(a.mapTo.indexOf(".")+1)]=a.fieldName)});return f.length?{fields:f,fieldsMap:k,comparisonLevels:c,calculatorName:d}:null}var e=[];b=w.optimizeInfos(b);b.forEach(function(a){var b;if(a.isGeneral||a.isChart)b=c(a.fields,a.levels,a.calculatorName);
b&&e.push(b)});if(e.length)return g(m.getCustomReportByID(a),function(b){function c(b){a.fieldData.errors.push(b)}return l(e.map(function(d){return(new r).enrichAreas({analysisAreas:a.analysisAreas,countryID:a.countryID,hierarchy:b.hierarchy,fields:d.fields,comparisonLevels:d.comparisonLevels}).then(function(b){h.addEnrichFeatureSet(b[0],d.fieldsMap,d.calculatorName,a)},c)}))})}}});