// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_ColumnBarChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartSorting ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ./_ComparisonUtil ./_AxisBuilder ./_PointLabelUtil".split(" "),function(F,v,B,C,x,G,H,I,A){return{calcSeriesColumnBar:function(a){var g=a.chart,h=a.visualProperties,c=a.seriesItems,n=1===c.length,w=a.seriesItemsWithComparison||
c,k=a.chartType,y=a.comparisonInfo,z=a.themeSettings,t=a.viewModel,p=1===w.length&&a.sorting,x=1<w.length&&h.renderColumnBarsInOppositeDirections,l=[],b={minYValue:Infinity,maxYValue:-Infinity,stackedValues:h.isStacked?[]:null};A.createPointToLabelMap(g);var u={};w.forEach(function(f,c){if(f.points.length){var m={name:f.label,data:[],isComparisonSeries:f.isComparisonSeries,params:{plot:f.isComparisonSeries&&H.getComparisonPlotName(k,y)||void 0}},d=this._collectStatisticsForSeries(a,f,c,b);v.provideMissingIconsForPoints(f.points,
k);var D=[];f.points.forEach(function(e,b){var g=d.values[b],p=g||0,l=b+1,r;h.conditionalStyling&&(r=(r=C.getConditionalStyle(p,h.conditionalStyling))&&r.backgroundColor);r=r||v.calcColorForPoint(e,f,b,c,n?1:2,k,z,f.isComparisonSeries,y);var q=G.getTooltipInfo({yValue:g,pointLabel:A.getPointLabel(e,t),seriesLabel:f.label,minInSeriesValue:d.minInSeries,maxInSeriesValue:d.maxInSeries,sumInSeriesValue:d.valuesSum,absSumInSeriesValue:d.absValuesSum,avgInSeriesValue:d.avgInSeries,minInAreasValue:d.minInSeries,
maxInAreasValue:d.maxInSeries,sumInAreasValue:d.valuesSum,absSumInAreasValue:d.absValuesSum,avgInAreasValue:d.avgInSeries,visualProperties:h,chartType:k,isMultiFeature:a.isMultiFeatureChart,color:r,conditionalStyling:h.conditionalStyling,fieldInfo:e.fieldInfo,isThisAreaSpecific:y&&!a.isMultiFeatureChart?!f.isComparisonSeries:void 0,isThisAreaSingleSeries:n,decimals:e.value&&e.value.decimals}),E=u[l]=u[l]||[];E.push(q);D.push(q);q.getGroup=function(){return a.isMultiFeatureChart?D:E};e={x:l,y:p*(x&&
c>=w.length/2?-1:1),originalValue:g,isUnavailableData:isNaN(g),valueProp:"y",unsortedIndex:b,seriesIndex:c,name:A.getPointLabel(e,t),_valuesSumsInSeries:d.absValuesSum,point:e,fill:r,tooltip:q,icon:v.calcIconForPoint(e,r,k),bgIcon:v.calcBackgroundIconForPoint(e,k,z,h),stroke:{width:0}};h.yAxis.showValuesAsWeightsInSeries&&(e.y/=d.absValuesSum/100);m.data.push(e)});p&&p!==B.NONE&&(m.data.sort(function(a,b){return(a.y-b.y)*(p===B.DESC?-1:1)}),m.data.forEach(function(a,b){a.x=b+1}));m.data.forEach(function(a){A.updatePointIndexToLabelMap(g,
a.x,a.point,t)});l.push(m)}},this);b.stackedValues&&(b.stackedValues.sort(function(a,b){return b-a}),b.minYValue=b.stackedValues[b.stackedValues.length-1],b.maxYValue=b.stackedValues[0]);I.prettifyYAxis(b.minYValue,b.maxYValue,h.yAxis.baseLineValue,g,h,k,z,t,l.length);a.plotStat&&(F.mixin(a.plotStat,b),a.plotStat.pointIndexToTooltipsHash=u);return l},_collectStatisticsForSeries:function(a,g,h,c){var n=a.visualProperties,w=a.viewModel,k=a.seriesItems,y=a.currentFeatureIndex,z=a.isMultiFeatureChart,
t=a.excludedSeriesHash&&a.excludedSeriesHash[g.label],p=a.selectedComparisonAreaId,v=a.ge,l=a.chartType;a=1<k.length&&n.renderColumnBarsInOppositeDirections;var b=2===k.length&&a?x.CHART_DATA_SMOOTH:null;n.conditionalStyling&&(a=C.getStatistics(n.conditionalStyling))&&k.length&&(b=x.getChartData(a,k[0].points.length,b,!1));var u=[],f=0,q=0,m=1E6,d=-1E6;g.points.forEach(function(a,e){a=x.getPreviewValue(a,e,h,!1,l,n,w,z?e:y,b,g.isComparisonSeries,p,v,!1);a=(u[e]=a)||0;t||(f+=a,q+=Math.abs(a),m=Math.min(m,
a),d=Math.max(d,a))});t||g.points.forEach(function(a,b){a=u[b];a=n.yAxis.showValuesAsWeightsInSeries?a/q*100:a;c.stackedValues?(c.stackedValues[b]=c.stackedValues[b]||0,c.stackedValues[b]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue))});return{values:u,valuesSum:f,absValuesSum:q,minInSeries:m,maxInSeries:d,avgInSeries:f/g.points.length}}}});