// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_LineChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartTypes ../../ChartLineStyles ../../ChartLineMarkers ../../AxisUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ../ChartPlots esri/dijit/geoenrichment/utils/ColorUtil ./_AxisBuilder ./_PointLabelUtil".split(" "),function(F,x,C,y,G,H,D,I,J,K,L,B){var M={calcLineStyle:function(a,g,m,c){var b=c.comparisonInfo,k=c.visualProperties;g=x.calcColorForPoint(null,
a,0,g,m.length,C.LINE,c.themeSettings,a.isComparisonSeries,b);m=k.lineThickness||1;k=k.fillLineArea?k.lineAreaOpacity:1;c=y.SOLID;var e=void 0;a.isComparisonSeries&&b&&(b.lineThickness&&(m=b.lineThickness),b.lineStyle&&(c=b.lineStyle),e=b.lineMarker?G.getMarkerPath(b.lineMarker):x.getComparisonSymbol());1>k&&g&&(g=K.toColor(g),g.a=k);return{color:g,width:m,style:y.toGFXValue(c),marker:e}}};return{calcSeriesLine:function(a){var g=a.chart,m=a.chartType,c=a.visualProperties,b=a.seriesItems,k=1===b.length,
e=a.seriesItemsWithComparison||b,q=a.isSecondaryPlot,z=a.reverseXY||m===C.VERTICAL_LINE,N=a.comparisonInfo,b=a.themeSettings,u=a.viewModel,r=[],f={minYValue:Infinity,maxYValue:-Infinity,stackedValues:c.isStacked?[]:null,crossSeriesStats:null},A=a.primaryPlotStat&&a.primaryPlotStat.pointIndexToTooltipsHash||{},n=e.map(function(c,h){return this._collectStatisticsForSeries(a,c,q?2*h+1:h,f)},this);f.crossSeriesStats=a.isMultiFeatureChart&&this._collectCrossSeriesStats(n);e.forEach(function(b,h){if(b.points.length){var v=
M.calcLineStyle(b,q?2*h+1:h,e,a),E={name:b.label,data:[],isComparisonSeries:b.isComparisonSeries,params:{plot:q?J.SECONDARY:void 0,stroke:{color:v.color,width:v.width,style:v.style},fill:v.color,outline:!1}},w=n[h];b.points.forEach(function(d,e){function r(){return q&&!a.oppositeDirections&&2===a.primarySeries.length?0===h?-.15:.15:0}var n=w.values[e],t=n||0,p=e+1;B.updatePointIndexToLabelMap(g,p,d,u);var l=a.isMultiFeatureChart&&f.crossSeriesStats[e],l=I.getTooltipInfo({yValue:n,pointLabel:B.getPointLabel(d,
u),seriesLabel:b.label,minInSeriesValue:w.minInSeries,maxInSeriesValue:w.maxInSeries,sumInSeriesValue:w.valuesSum,absSumInSeriesValue:w.absValuesSum,avgInSeriesValue:w.avgInSeries,minInAreasValue:l&&l.min,maxInAreasValue:l&&l.max,sumInAreasValue:l&&l.sum,absSumInAreasValue:l&&l.absSum,avgInAreasValue:l&&l.avg,visualProperties:c,chartType:m,isMultiFeature:a.isMultiFeatureChart,color:v.color,conditionalStyling:null,fieldInfo:d.fieldInfo,isThisAreaSpecific:N&&!a.isMultiFeatureChart?!b.isComparisonSeries:
void 0,isThisAreaSingleSeries:k,decimals:d.value&&d.value.decimals}),x=A[p]=A[p]||[];x.push(l);l.getGroup=function(){return x};d={originalValue:n,isUnavailableData:isNaN(n),unsortedIndex:e,seriesIndex:h,name:B.getPointLabel(d,u),_valuesSumsInSeries:w.absValuesSum,point:d,fill:"#FFFFFF",stroke:{color:v.color,width:1,style:y.toGFXValue(y.SOLID)},outline:!1,tooltip:l};u.isGraphicStyle?v.marker&&(d.marker=v.marker):d.marker=void 0;z?(d.x=t*(q&&a.oppositeDirections&&1===h?-1:1),d.y=p+r(),d.valueProp="x"):
(d.x=p+r(),d.y=t*(q&&a.oppositeDirections&&1===h?-1:1),d.valueProp="y");c.yAxis.showValuesAsWeightsInSeries&&(d[z?"x":"y"]/=w.absValuesSum/100);E.data.push(d)});r.push(E)}},this);f.stackedValues&&(f.stackedValues.sort(function(a,h){return h-a}),f.minYValue=f.stackedValues[f.stackedValues.length-1],f.maxYValue=f.stackedValues[0]);if(q){if(a.primaryPlotStat&&(b=H.getPrettifyYAxisParameters(Math.min(f.minYValue,a.primaryPlotStat.minYValue),Math.max(f.maxYValue,a.primaryPlotStat.maxYValue),{baseLineValue:c.yAxis.baseLineValue,
renderColumnBarsInOppositeDirections:a.oppositeDirections,previewBelowZero:!u.dynamicReportInfo}),F.mixin(g.axes.y.opt,{majorTickStep:b.majorTickStep,minorTickStep:b.minorTickStep,min:b.min,max:b.max})),1===a.primarySeries.length){var p=z?"y":"x",t=[];a.primarySeries[0].data.forEach(function(a){var h=r[0].data[a.unsortedIndex];h[p]=a.x;t.push(h)});r[0].data=t}}else L.prettifyYAxis(f.minYValue,f.maxYValue,c.yAxis.baseLineValue,g,c,m,b,u);return r},_collectStatisticsForSeries:function(a,g,m,c){var b=
a.chartType,k=a.viewModel,e=a.visualProperties,q=a.currentFeatureIndex,z=a.isMultiFeatureChart,x=a.selectedComparisonAreaId,u=a.isSecondaryPlot,r=a.ge,f=[],A=0,n=0,p=1E6,t=-1E6,y=2===a.seriesItems.length&&a.oppositeDirections&&u?D.CHART_DATA_SMOOTH:null;g.points.forEach(function(a,c){a=D.getPreviewValue(a,c,m,!1,b,e,k,z?m:q,y,g.isComparisonSeries,x,r,!1);a=(f[c]=a)||0;A+=a;n+=Math.abs(a);p=Math.min(p,a);t=Math.max(t,a)});g.points.forEach(function(a,b){a=f[b];a=e.yAxis.showValuesAsWeightsInSeries?
a/n*100:a;c.stackedValues?(c.stackedValues[b]=c.stackedValues[b]||0,c.stackedValues[b]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue))});return{values:f,valuesSum:A,absValuesSum:n,minInSeries:p,maxInSeries:t,avgInSeries:A/g.points.length}},_collectCrossSeriesStats:function(a){return a.length?a[0].values.map(function(g,m){var c=0,b=0,k=1E6,e=-1E6;a.forEach(function(a){a=a.values[m]||0;c+=a;b+=Math.abs(a);k=Math.min(k,a);e=Math.max(e,a)});return{sum:c,absSum:b,min:k,max:e,
avg:c/a.length}}):[]}}});