// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartJsonUtil","dojo/_base/lang ./ThemeCalculator ./ChartTypes ./ChartDataLabelsTypes ../legends/ChartLegendPlacements ../legends/ChartLegendTypes ./_ChartJsonCleaner ./_ChartJsonClassicReportSupports esri/dijit/geoenrichment/utils/ObjectUtil ./plots/supportClasses/GaugeLabelPlacement ../../../dataProvider/supportClasses/AreaDataUtil".split(" "),function(c,d,g,m,h,n,p,q,k,r,l){var f={getDefaultChartSettings:function(b){b=b||{};var a=
c.mixin({},b.font),e=c.mixin({},b.font);delete e.fontSize;return{isChart:!0,type:b.chartType||g.COLUMN,isMultiFeatureChart:!!b.isMultiFeatureChart,seriesItems:b.seriesItems||[],visualProperties:{width:b.width||400,height:b.height||300,barBorders:!1,view3D:!1,origin:0,backgroundColor:void 0,backgroundImageData:void 0,panelBackgroundColor:void 0,title:{text:"",align:"center",style:c.mixin({},a),verticalShift:0},xAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:c.mixin({},a),
style:c.mixin({},a),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,placement:void 0},yAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:c.mixin({},a),style:c.mixin({},a),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,
gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,baseLine:!0,baseLineColor:void 0,baseLineOpacity:1,baseLineThickness:.5,baseLineStyle:void 0,baseLineValue:0,showPercentIndicator:!1,showValuesAsWeightsInSeries:!1,placement:void 0},legend:{type:n.SERIES,series:{placement:h.RIGHT,placementOffset:10,hasBorder:!0,labelParts:"Label",style:c.mixin({},a)},minMax:{placement:h.RIGHT,placementOffset:3,titleStyle:c.mixin({},e),minVariableLabelStyle:c.mixin({},e),maxVariableLabelStyle:c.mixin({},
e)}},isStacked:!1,columnThickness:d.DEFAULT_COLUMN_THICKNESS,showColumnBarBackground:!1,columnBarBackgroundColor:void 0,renderColumnBarsInOppositeDirections:!1,columnBarGap:void 0,lineThickness:d.DEFAULT_LINE_THICKNESS,fillLineArea:!1,lineAreaOpacity:1,donutHolePercent:d.DEFAULT_DONUT_HOLE_PERCENT,donutGap:d.DEFAULT_DONUT_GAP,donutArcPercent:d.DEFAULT_DONUT_ARC_PERCENT,gaugeHolePercent:d.DEFAULT_GAUGE_HOLE_PERCENT,gaugeRangeMin:void 0,gaugeRangeMax:void 0,gaugeGap:d.DEFAULT_GAUGE_GAP,gaugeStartAngle:d.DEFAULT_GAUGE_ANGLE,
gaugeArcPercent:d.DEFAULT_GAUGE_ARC_PERCENT,gaugeLabelPlacement:r.INSIDE,gaugeLabelStyle:c.mixin({},e),gaugeShowArrow:!1,gaugeArrowLineColor:void 0,gaugeArrowFillColor:void 0,gaugeConditionalStylingIgnoreOthers:!1,gaugeConditionalStylingLabel:!1,gaugeShowFromToLabels:!1,gaugeFromLabelStyle:c.mixin({},e),gaugeToLabelStyle:c.mixin({},e),ringBackgroundColor:void 0,showWholePictures:!1,dataLabels:m.NONE,dataLabelsStyle:c.mixin({},a),dataLabelsDecimals:0,dataLabelsInside:!1,dataLabelsStackedInColumns:!1,
dataLabelsHorizontalAlign:void 0,chartIcons:void 0,floatingIcons:void 0,showAxisIcons:!1,showChartIcons:!1,floatingTexts:void 0,sorting:void 0,conditionalStyling:void 0},comparisonInfo:void 0}},provideDefaultValueForMissing:function(b,a){a=f.getDefaultChartSettings(a);k.populateObject(b,a);return b},cleanUpJson:function(b,a){p.cleanUpJson(b,a)},filterChartJsonForClassicReport:function(b){return k.filterByPattern(b,q)},createChartPoint:function(b,a,c,d,t){return{color:c||"",label:void 0!==a?a||"":
b&&b.alias,fieldInfo:b,iconFieldInfo:d,captionFieldInfo:t}}},u=[{headers:{data:{AREA_DESC:"1 mile"}}},{headers:{data:{AREA_DESC:"3 miles"}}},{headers:{data:{AREA_DESC:"5 miles"}}}];f.getSeriesItemsForMultiFeatureChart=function(b,a,e){if(!a||!a.length)return a;e=e||u;var d=a[0];return g.isLineLike(b)?e.map(function(b){var a=c.clone(d);a.color=d.points[0].color;a.points.forEach(function(a){delete a.color});a.label=l.getAreaDataValue({areaDataObject:b,fieldName:"AREA_DESC"})||"";return a}):d.points.map(function(a){return{label:a.label,
thickness:d.thickness,points:e.map(function(b){return f.createChartPoint(a.fieldInfo,l.getAreaDataValue({areaDataObject:b,fieldName:"AREA_DESC"})||"",a.color||d.color)})}})};f.getOriginalPointByMultiFeatureIndexes=function(b,a,c){return b[0].points[a]};return f});