// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/tasks/EnrichAreasTask","dojo/_base/declare dojo/_base/lang dojo/when dojo/promise/all esri/kernel esri/SpatialReference ../GEUtil ../AnalysisAreaUtil ./parsers/FeatureSetParser ../../../core/supportClasses/map/Projector esri/dijit/geoenrichment/utils/CoordinateUtil".split(" "),function(p,h,e,q,r,k,t,m,u,v,l){function n(){var a=r.id.credentials[0];return a&&a.token}return p(null,{enrichAreas:function(a){var b={};return e(this._analysisAreasToStudyAreas(a.analysisAreas,
a.countryID,a.comparisonLevels),function(d){b.studyAreas=d;a.report?b.analysisVariables=[{itemid:a.report.reportID,url:a.report.portalUrl,token:n(),outFields:["*"]}]:a.fields&&(b.analysisVariables=a.fields);return this._doRunTask(b,a,"enrich")}.bind(this))},createReport:function(a){var b={f:"bin",format:"xml",reportfields:{}};b.report={itemid:a.report.reportID,url:a.report.portalUrl,token:n()};return e(this._analysisAreasToStudyAreas(a.analysisAreas,a.countryID),function(d){b.studyAreas=d;return this._doRunTask(b,
a,"createReport")}.bind(this))},_analysisAreasToStudyAreas:function(a,b,d){var g=this;d=d&&d.map(function(a){return{layer:a}});return q(a.map(function(a,f){var c;c=a.geographies&&a.geographies.length?g._studyAreaFromGeographies(a.geographies,b,!0):{attributes:h.mixin({},a.feature.attributes),geometry:a.feature.geometry.toJson()};d&&(c.comparisonLevels=d);return e(g._getStorePointForArea(a),function(b){b&&(c.attributes=c.attributes||{},c.attributes.STORE_LAT=c.attributes.STORE_LAT||b.STORE_LAT,c.attributes.STORE_LONG=
c.attributes.STORE_LONG||b.STORE_LONG);a.geographies||(c.attributes=c.attributes||{},c.attributes.STORE_ID=f);c.attributes&&u.ID_FIELDS.forEach(function(a){delete c.attributes[a]});return c})}))},_getStorePointForArea:function(a){if(a.location){var b=m.geometryToLatLong(a.location.geometry);return b?b:e(v.projectGeometries(a.location.geometry,new k(l.WGS_84_WKID)),function(a){return m.geometryToLatLong(a)})}},createFeatureForGeographies:function(a,b){return this._createFeaturesForGeographies(a,b,
!0)},createFeaturesForGeographies:function(a,b){return this._createFeaturesForGeographies(a,b,!1)},_createFeaturesForGeographies:function(a,b,d){a={returnGeometry:!0,outSR:b.outSR||new k(l.WEB_MERCATOR_WKID),studyAreas:d?[this._studyAreaFromGeographies(a,b.countryID,!0,b.generalizationLevel)]:a.map(function(a){return this._studyAreaFromGeographies([a],b.countryID,!1,b.generalizationLevel)},this),dataCollections:["GlobalIntersect"]};return this._doRunTask(a,b,"enrich")},_studyAreaFromGeographies:function(a,
b,d,g){b={sourceCountry:b,layer:null,ids:null,attributes:null};var e=null,f=[],c;a.forEach(function(a){if(!a||!a.id)throw Error("Wrong geography.");var b=a.levelId;if(b)if(!e)e=b;else if(d&&e!==b)throw Error("Geographies have different level IDs.");f.push(a.id);a.attributes&&(c=h.mixin(c||{},a.attributes))});b.layer=e;b.ids=d?[f.join(",")]:f;b.attributes=c;b.generalizationlevel=g;return b},createFeatureForBuffer:function(a,b){a={returnGeometry:!0,outSR:b.outSR||a.point.spatialReference||new k(l.WEB_MERCATOR_WKID),
dataCollections:["GlobalIntersect"],studyAreasOptions:{bufferUnits:a.units,bufferRadii:[a.radius],areaType:"RingBuffer"},studyAreas:[{geometry:a.point.toJson?a.point.toJson():a.point}]};return this._doRunTask(a,b,"enrich")},_doRunTask:function(a,b,d){a=h.mixin({f:"json",useData:{sourceCountry:b.countryID,hierarchy:b.hierarchy||"census"},forStorage:!1},a);for(var e in a)(b=a[e])&&"object"===typeof b&&(a[e]=JSON.stringify("function"===typeof b.toJson?b.toJson():b));return t[d](a)}})});