// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/comparison/ComparisonSelect","dojo/_base/declare dojo/on dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/OnDemandSelect ../../dataProvider/supportClasses/AreasInfoTemplateBuilder ./ComparisonListUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/TooltipUtil".split(" "),function(h,k,l,e,m,p,f,n,d){var q=h(m.itemRenderers.DefaultItemRenderer,{createLabelNode:!0,createImageAfterLabel:!0,fields:null,addFeatureMessage:null,
featureIsAlreadyAddedMessage:null,removeFeatureMessage:null,canAddFeatures:!1,canRemoveFeatures:!1,_createImageNode:function(b,a){var g=this;if(b.isArea){if(this.fields&&!n.isMobileDevice()){var c=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_infoIcon"},a);d.setTooltipToNode(c,function(){return g._buildGeographyTooltip(b)},{isComplexTooltip:!0})}this.canRemoveFeatures&&(c=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_removeButton"},
a),this.isAdded(b)&&this.canRemoveFeature(b)?(k(c,"click",function(a){a.stopPropagation();g.onRemoveFeature(b)}),d.setTooltipToNode(c,this.removeFeatureMessage)):l.add(c,"disabled"));this.canAddFeatures&&(a=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_addButton"},a),this.isAdded(b)?(l.add(a,"disabled"),d.setTooltipToNode(a,this.featureIsAlreadyAddedMessage)):(k(a,"click",function(a){a.stopPropagation();g.onAddFeature(b)}),d.setTooltipToNode(a,this.addFeatureMessage)))}},
_buildGeographyTooltip:function(b){var a=this.fields.map(function(a){return{label:a.label,value:a.formatFunction(b.attributes[a.name])}});return p.buildAttributesTable(null,a,{padding:10})},isAdded:function(b){},onAddFeature:function(b){},canRemoveFeature:function(b){},onRemoveFeature:function(b){}});return h(m,{listClass:"esriGEOnDemandSelectSpacedOut esriGEOnDemandSelectVeryTallList600",fields:null,addFeatureMessage:null,featureIsAlreadyAddedMessage:null,removeFeatureMessage:null,canAddFeatures:!1,
canRemoveFeatures:!1,showTitleForSingleGroup:!1,buildRendering:function(){var b=this;n.isMobileDevice()&&(this.listClass+=" esriGEComparisonSelectListMobile");var a=new q;a.fields=this.fields;a.addFeatureMessage=this.addFeatureMessage;a.featureIsAlreadyAddedMessage=this.featureIsAlreadyAddedMessage;a.canAddFeatures=this.canAddFeatures;a.isAdded=function(a){return b.isFeatureAdded(a.levelId,a.value)};a.onAddFeature=function(a){b.closePopup();b.onAddFeature(a.levelId,a.value)};a.canRemoveFeatures=this.canRemoveFeatures;
a.removeFeatureMessage=this.removeFeatureMessage;a.canRemoveFeature=function(a){return b.canRemoveFeature(a.levelId,a.value)};a.onRemoveFeature=function(a){b.closePopup();b.onRemoveFeature(a.levelId,a.value)};this.itemRenderer=a;this.inherited(arguments)},setGroups:function(b){this.set("options",f.getOptionsFromGroups(b,{hideTitleForSingleGroup:!this.showTitleForSingleGroup}))},setFeatures:function(b){this.set("options",f.getListOptionsFromFeatures(b))},setDefaultValue:function(){var b=f.getDefaultOptionValue(this.options);
this.set("value",b);return b},isFeatureAdded:function(b,a){return!1},canRemoveFeature:function(b,a){return!0},onChange:function(){var b=this.getSelectedItem();this.onFeatureSelected(b.levelId,b.value)},onFeatureSelected:function(b,a){},onAddFeature:function(b,a){},onRemoveFeature:function(b,a){}})});