// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.26/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/DataProviderGE","dojo/_base/declare dojo/_base/lang dojo/promise/all dojo/when ./dataProvider/_CommandSupport ./dataProvider/_SerializationSupport ./dataProvider/_ServerSerializationSupport ./dataProvider/supportClasses/AnalysisAreaUtil ./dataProvider/supportClasses/AnalysisAreaJsonUtil ./dataProvider/supportClasses/CustomReportsManager ./dataProvider/supportClasses/TemplateJsonLoader ./dataProvider/supportClasses/ReportDataProcessor ./dataProvider/supportClasses/InfographicOptionsProvider ./dataProvider/supportClasses/AreasPreprocessor ./dataProvider/supportClasses/GEUtil ./dataProvider/supportClasses/attachments/DefaultAttachmentsStore ./dataProvider/supportClasses/attachments/CustomAttachmentsStore ./dataProvider/supportClasses/StandardGraphicReportTemplates ./dataProvider/supportClasses/PortalManager ./core/themes/ThemeLibrary ./core/themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/utils/ProjectionUtil".split(" "),
function(t,f,u,p,v,w,x,y,h,g,z,k,A,B,l,C,D,E,F,G,q,m,H){return t([v,w,x],{analysisAreasLimit:-1,cacheTemplates:!0,printMapTaskUrl:null,resetReportItemsCache:!0,_infographicOptionsProvider:null,constructor:function(b){f.mixin(this,b);this._infographicOptionsProvider=new A},_getAttachmentsStore:function(b){return(new C(b)).initialize()},getCustomReports:function(b,d){return g.getCustomReports(b,d)},_currentContext:null,getReportData:function(b,d){var c=this;d=d||function(){};var a=f.mixin({},b);a.reportID=
E.aliasToID(a.countryID,a.reportID)||a.reportID;a.analysisAreas=h.areasFromJson(a.analysisAreas);a.combinedAreasInfo=a.combinedAreasInfo&&h.combinedAreasInfoFromJson(a.combinedAreasInfo)||{};y.pppulateCombinedAreasInfo(a.combinedAreasInfo,a.analysisAreas);a.fieldData={runReportTaskID:null,metadata:{},areaData:[],errors:[]};this._currentContext=a;this.resetReportItemsCache&&g.resetCache();return p(F.getPortalInfo(a.portalUrl),function(b){a.geoenrichmentUrl=a.geoenrichmentUrl||b.portal.helperServices.geoenrichment.url;
l.setGeoenrichmentUrl(a.geoenrichmentUrl);c._infographicOptionsProvider.setServerUrl(a);var r=a.geometryServiceUrl||b.portal.helperServices.geometry.url;H.setGeometryServiceUrl(r);return p(B.preprocessAreas(a,{analysisAreasLimit:c.analysisAreasLimit}),function(){d(.25);setTimeout(function(){c._onCreateReportStarted()});return u({initGE:l.initialize(),countryInfo:l.getCountryInfo(a.countryID),reportObject:g.getCustomReportByID(a),infographicOptions:c._infographicOptionsProvider.getInfographicOptions(a),
attachmentsStore:a.attachmentsProvider?D(a.attachmentsProvider):c._getAttachmentsStore(a.analysisAreas),templateJsonInfo:z.getTemplateJsonByID(a,c.cacheTemplates),runReportResult:k.runReportAndGetData(a)}).then(function(b){var c=b.reportObject,e=b.infographicOptions,f=b.attachmentsStore,n=b.templateJsonInfo.templateJson,g=b.templateJsonInfo.templateVariableProvider,h=b.runReportResult;d(.75);if(!n||!c||!a.fieldData)return null;k.applyRunReportAndGetDataResults(h,a);m.setCountry(b.countryInfo.country);
m.setHierarchyID(c.hierarchy);m.setGeographiesModel(b.countryInfo.geographiesModels[m.getHierarchyID()]);return p(f&&k.populateReportDataFromAttachmentsStore(a,f),function(){d(1);n.theme||(n.theme=G.getReportThemeById(c.isGraphicReport?q.GRAPHIC:q.CLASSIC));return{isClassic:!c.isGraphicReport,isMultiFeature:c.isMultiFeature&&1<a.analysisAreas.length,reportType:c.type,reportTitle:c.title,templateJson:n,reportObject:c,fieldData:a.fieldData,analysisAreas:a.analysisAreas,combinedAreasInfo:a.combinedAreasInfo,
reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,infographicOptions:e,attachmentsStore:f,geClient:l.getClient(),templateVariableProvider:g,config:{portalUrl:a.portalUrl,geoenrichmentUrl:a.geoenrichmentUrl,geometryServiceUrl:r,countryID:a.countryID,hierarchy:c.hierarchy,reportID:a.reportID}}})})})})},reportDataToSingleAreaReportData:function(b,d){var c=d.currentFeatureIndex||0,a=f.mixin({},b.fieldData);a.areaData=[a.areaData[c]];var g=[b.analysisAreas[c]],h=b.infographicOptions&&this._infographicOptionsProvider.getInfographicOptionsFromJson(b.infographicOptions.toJsonAt(c)),
e=b.attachmentsStore;return{isClassic:b.isClassic,isMultiFeature:!1,reportType:b.reportType,reportTitle:d.reportTitle,templateJson:d.templateJson,reportObject:b.reportObject,fieldData:a,analysisAreas:g,combinedAreasInfo:null,reverseAnalysisAreasOnMap:!1,infographicOptions:h,attachmentsStore:e&&{getAttachments:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);return e.getAttachments()},getAttributes:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);
return e.getAttributes()},getNotes:function(){e.setCurrentAnalysisAreaIndex&&e.setCurrentAnalysisAreaIndex(c);return e.getNotes()}},geClient:b.geClient,templateVariableProvider:b.templateVariableProvider,config:b.config}},_getCurrentContext:function(){return this._currentContext},_onCreateReportStarted:function(){},enrichFieldData:function(b,d){return k.enrichFieldData(b,d)}})});